name: CI

on:
  push:
    branches:
      - main
      - "lib-dev-phase_*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Show Go version
        run: go version

      - name: Check code formatting
        run: test -z "$(gofmt -l .)"

      - name: Run static analysis (go vet)
        run: go vet ./...

      - name: Run unit tests
        run: go test -race -count=1 -v ./...

      - name: Install nats-server
        run: |
          sudo apt-get update
          sudo apt-get install -y nats-server

      - name: Show nats-server version
        run: nats-server --version

      - name: Run integration tests
        run: go test -race -count=1 -v -tags=integration ./tests/integration/...
